RhythmRally/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash
from .forms import LoginForm, RegisterForm
from flask_login import current_user, login_required, logout_user, login_user
from flask_bcrypt import generate_password_hash, check_password_hash
from .models import User
from . import db, bcrypt
from sqlalchemy import select


# create a blueprint
authbp = Blueprint('auth', __name__ )
@authbp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        # Hash the password entered by the user
        hashed_password = generate_password_hash(form.password.data).decode('utf-8')

        # Create a new user instance with the hashed password
        new_user = User(
            first_name=form.first_name.data,
            surname=form.surname.data,
            email=form.email.data,
            password_hash=hashed_password,  # Store the hashed password
            contact_number=form.contact_number.data,
            street_address=form.street_address.data
        )

        # Add the user to the session and commit it to the database
        db.session.add(new_user)
        db.session.commit()

        flash('Registration successful. Please log in.', 'success')
        return redirect(url_for('auth.login'))

    return render_template('user.html', form=form, heading='Register')

    



@authbp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        # Get the email and password from the form
        user_email = form.email.data
        user_password = form.password.data

        # Query the user from the database by email
        user = db.session.scalar(db.select(User).where(User.email == user_email))

        # If the user doesn't exist or the password is incorrect
        if user is None:
            flash('Incorrect email. Please try again.', 'danger')
        elif not bcrypt.check_password_hash(user.password_hash, user_password):
            flash('Incorrect password. Please try again.', 'danger')
        else:
            # Log the user in using Flask-Login
            login_user(user)
            flash('Logged in successfully!', 'success')
            return redirect(url_for('main.home'))

    return render_template('user.html', form=form, heading='Login')


@authbp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.home'))

RhythmRally/views.py
from flask import Blueprint, request, redirect, url_for, flash, render_template, send_from_directory
from . import db
from .forms import RegisterForm
from .models import Event, Review, Purchase
from flask_login import current_user, login_required
from datetime import datetime
from sqlalchemy import select


# Create a Blueprint
mainbp = Blueprint('main', __name__)

# Define routes using the Blueprint\

@mainbp.route("/")
def home():
    events = db.session.scalars(select(Event)).all()
    for event in events:
        event.update_event_state()
    db.session.commit()
    return render_template("index.html", events = events)

@mainbp.route("/history")
@login_required
def booking_history():
    user_purchases = db.session.scalars(select(Purchase).where(Purchase.user_id == current_user.user_id)).all()
    return render_template("bookinghistory.html", purchases = user_purchases)

RhythmRally/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" href="{{ url_for('static', filename='style/style.css') }}">

    <title>Rhythm Rally Home</title>
</head>
    
<style>
    .body {
        padding-top: 80px;
    }
    
    .custom-padding {
        padding: 0;
        overflow-x: hidden;
    }
</style>
    
<body class="{{ body_class | default('default-padding') }}">
    
    <!-- NAVIGATION BAR -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light py-3 fixed-top">
        <a class="navbar-brand" href="{{ url_for('main.home') }}">Rhythm Rally</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.home') }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('event.list_events') }}">Events</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('event.create_event') }}">Create Event</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.booking_history') }}">Booking History</a>
                </li>
                <!-- Check if the user is logged in -->
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

{% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="container-fluid mt-5">
        <div class="row justify-content-center mt-3 mb-3">
            <div class="col-md-12">
                {% for message in messages %}
                    <div class="alert alert-info">
                        {{message}}
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endif %}
{% endwith %}

    <!-- Main Content -->
    <main class="container mt-5">
        {% block content %}
        {% endblock %}
    </main>

    <!-- FOOTER -->
    <footer class="mt-5 py-5">
        <div class="row container mx-auto pt-5">
            <div class="footer-one col-lg-3 col-md-6 col-12">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore
                    et dolore magna aliqua.</p>
            </div>
            <div class="footer-one col-lg-3 col-md-6 col-12">
                <h5 class="pb-2">Categories</h5>
                <ul class="text-uppercase list-unstyled">
                    <li><a href="#">Rock</a></li>
                    <li><a href="#">Pop</a></li>
                    <li><a href="#">Country</a></li>
                    <li><a href="#">RnB</a></li>
                    <li><a href="#">HipHop</a></li>
                </ul>
            </div>
            <div class="footer-one col-lg-3 col-md-6 col-12">
                <h5 class="pb-2">Contact Us</h5>
                <div>
                    <h6 class="text-uppercase">Address</h6>
                    <p>123 STREET NAME, CITY, AUSTRALIA</p>
                </div>
                <div>
                    <h6 class="text-uppercase">Phone</h6>
                    <p>(64+) 0412345678</p>
                </div>
                <div>
                    <h6 class="text-uppercase">Email</h6>
                    <p>emailaddress@example.com</p>
                </div>
            </div>
            <div class="footer-one col-lg-3 col-md-6 col-12">
                <h5 class="pb-2">Socials</h5>
                <div class="row">
                    <img class="img-fluid w-25 h-100 m-2" src="{{ url_for('static', filename='Images/instagram.jpg') }}" alt="">
                    <img class="img-fluid w-25 h-100 m-2" src="{{ url_for('static', filename='Images/twitter.jpg') }}" alt="">
                    <img class="img-fluid w-25 h-100 m-2" src="{{ url_for('static', filename='Images/youtube.jpg') }}" alt="">
                </div>
            </div>
        </div>
    </footer>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>

</html>

RhythmRally/templates/bookinghistory.html
{% extends "base.html" %}

{% set body_class = "body" %}

{% from 'bootstrap5/form.html' import render_form %}

{% block content %}
  <!-- BOOKING HISTORY -->
<section class="body">

    <div class="container text-center mt-5 py-5">
        <h3>User Booking History</h3>
        <hr>
        <p>Browse Your Latest Booked Events</p>
      </div>

    <div class="container cart-page">
      <table class="table table-bordered">
        <thead>
            <tr>
                <th>Events</th>
                <th>Date Boooked</th>
                <th>Time Booked</th>
                <th>Booking ID</th>
                <th>Tickets Purchased</th>
                <th>Subtotal</th>
            </tr>
            <tr>
                <td>
                    <div class="cart-info">
                        <img src="static/Images/albumcover2.jpg">
                        <div>
                            <p>Keshi Requiem WORLD TOUR</p>
                            <small>Location : 'Venue'</small>
                            <a href="">Cancel</a>
                        </div>
                    </div>

                </td>
                <td>DD/MM/YY</td>
                <td>24:00</td>
                <td>#abc1234567</td>
                <td>3</td>
                <td>$00:00</td>
            </tr>
            <tr>
                <td>
                    <div class="cart-info">
                        <img src="static/Images/albumcover3.jpg">
                        <div>
                            <p>'EVENTS NAME'</p>
                            <small>'Location' : 'Venue'</small>
                            <a href="">Cancel</a>
                        </div>
                    </div>

                </td>
                <td>DD/MM/YY</td>
                <td>24:00</td>
                <td>#abc1234567</td>
                <td>2</td>
                <td>$00:00</td>
            </tr>
            <tr>
                <td>
                    <div class="cart-info">
                        <img src="static/Images/albumcover4.jpg">
                        <div>
                            <p>'EVENT NAME'</p>
                            <small>'Location' : 'Venue'</small>
                            <a href="">Cancel</a>
                        </div>
                    </div>

                </td>
                <td>DD/MM/YY</td>
                <td>24:00</td>
                <td>#abc1234567</td>
                <td>2</td>
                <td>$00:00</td>
            </tr>
        </table>

        <div class="total-price">

            <table>
                <tr>
                    <td>Subtotal</td>
                    <td>$00.00</td>
                </tr>
                <tr>
                    <td>Tax</td>
                    <td>$00.00</td>
                </tr>
                <tr>
                    <td>Total</td>
                    <td>$00.00</td>
                </tr>
            </table>

        </div>

    </div>


</section>


{% endblock %}

RhythmRally/templates/create_event.html
{% extends 'base.html' %}

{% set body_class = "body" %}

{% from 'bootstrap5/form.html' import render_form %}

{% block content %}

<div class="container">
    <div class="row mt-5">
    <div class="col-md-12">
        <h1>Create an Event</h1>
        <p>Enter an event</p>
        {{ render_form(form) }}
    </div>
    </div>
</div>

{% endblock %}

RhythmRally/templates/eventdetails.html
{% extends "base.html" %}
{% from 'bootstrap5/form.html' import render_form %}
{% block content %}
  <div class="container mt-5">
    <!-- Event Details Section -->
    <div class="card mb-4">
      <div class="card-body">
        <h1 class="card-title">{{ event.event_name }}</h1>
        <img src="{{ url_for('static', filename=event.event_image) }}" alt="{{ event.event_name }}" class="img-fluid mb-4">
        
        <p class="card-text"><strong>Artist:</strong> {{ event.artist_name }}</p>
        <p class="card-text"><strong>Venue:</strong> {{ event.event_venue }}</p>
        <p class="card-text"><strong>Date:</strong> {{ event.event_date.strftime('%Y-%m-%d') }}</p>
        <p class="card-text"><strong>Start Time:</strong> {{ event.event_start_time[:5] }}</p>
        <p class="card-text"><strong>End Time:</strong> {{ event.event_end_time[:5] }}</p>
        <p class="card-text"><strong>Event State:</strong> {{ event.event_state }}</p>
        
      </div>
    </div>

    <form method="POST">
      <h2>{{ event.event_name }}</h2>
      <p>Price per ticket: ${{ event.event_ticket_price }}</p>
      <p>Tickets available: {{ event.tickets_available }}</p>
      <div class="form-group">
          <label for="num_tickets">Number of Tickets:</label>
          <input type="number" id="num_tickets" name="num_tickets" min="1" max="{{ event.tickets_available }}" required>
      </div>
      <button type="submit" class="btn btn-primary">Buy Tickets</button>
  </form>

    <!-- Reviews Section -->
    <div class="reviews-section mb-4">
      <h3>Reviews</h3>
      {% if reviews %}
        {% for review in reviews %}
          <div class="card my-3">
            <div class="card-body">
              <p class="mb-1"><strong>{{ review.user.first_name }} {{ review.user.surname }}</strong> says:</p>
              <p>{{ review.comment }}</p>
              <p><strong>Rating:</strong> {{ review.rating }}/5</p>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <p>No reviews yet. Be the first to review this event!</p>
      {% endif %}
    </div>

    <!-- Review Form Section -->
    <div class="review-form-section">
      <h4>Leave a Review</h4>
      <form method="POST" action="{{ url_for('event.submit_review', event_id=event.event_id) }}">
        {{ form.hidden_tag() }}
        <div class="mb-3">
          {{ form.review_rating.label(class="form-label") }}
          {{ form.review_rating(class="form-select") }}
        </div>
        <div class="mb-3">
          {{ form.review_comment.label(class="form-label") }}
          {{ form.review_comment(class="form-control") }}
        </div>
        <div>
          {{ form.submit(class="btn btn-primary mt-3") }}
        </div>
      </form>
    </div>
  </div>
{% endblock %}

RhythmRally/templates/events.html
{% extends "base.html" %}

{% set body_class = "body" %}

{% from 'bootstrap5/form.html' import render_form %}

{% block content %}
<div class="container mt-5">
    <h1>All Events</h1>
    <div class="row">
        {% for event in events %}
            <div class="col-md-4">
                <div class="card mb-4">
                    <img src="{{ url_for('static', filename='uploads/' + event.event_image.split('/')[-1]) }}" class="card-img-top" alt="{{ event.event_name }}">
                    <div class="card-body">
                        <h5 class="card-title">{{ event.event_name }}</h5>
                        <p class="card-text">Artist: {{ event.artist_name }}</p>
                        <p class="card-text">Venue: {{ event.event_venue }}</p>
                        <p class="card-text">Date: {{ event.event_date.strftime('%d-%m-%Y') }}</p>
                        <a href="{{ url_for('event.event_details', event_id=event.event_id) }}" class="btn btn-primary">View Details</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

RhythmRally/templates/eventupdate.html
{% extends "base.html" %}

{% set body_class = "body" %}

{% from 'bootstrap5/form.html' import render_form %}

{% block content %}
<div class="container mt-4">
    <h2>Update Event</h2>
    <form method="POST" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        
        <div class="mb-3">
            {{ render_form(form.event_name, label="Event Name") }}
        </div>
        <div class="mb-3">
            {{ render_form(form.artist_name, label="Artist Name") }}
        </div>
        <div class="mb-3">
            {{ render_form(form.event_venue, label="Event Venue") }}
        </div>
        <div class="mb-3">
            {{ render_form(form.description, label="Description") }}
        </div>
        <div class="mb-3">
            {{ render_form(form.image, label="Event Image") }}
            {% if event.image %}
                <img src="{{ url_for('static', filename=event.image) }}" alt="Event Image" style="width: 150px; margin-top: 10px;">
            {% endif %}
        </div>
        <div class="mb-3">
            {{ render_form(form.date, label="Event Date") }}
        </div>
        <div class="mb-3">
            {{ render_form(form.start_time, label="Start Time") }}
        </div>
        <div class="mb-3">
            {{ render_form(form.end_time, label="End Time") }}
        </div>
        <div class="mb-3">
            {{ render_form(form.ticket_price, label="Ticket Price") }}
        </div>
        <div class="mb-3">
            {{ render_form(form.number_of_tickets, label="Number Of Tickets") }}
        </div>
        <div class="mb-3">
            {{ render_form(form.category, label="Category") }}
        </div>
        
        <button type="submit" class="btn btn-primary">Update Event</button>
    </form>
</div>
{% endblock %}

RhythmRally/templates/index.html
{% extends "base.html" %}

{% set body_class = "custom-padding" %}

{% from 'bootstrap5/form.html' import render_form %}

{% block content %}

<!-- HERO BANNER -->
<section id="home" style="background-image: url('static/Images/background.jpg');">
    <div class="text-container" style="padding-left: 100px;">
        <h5>UPCOMING EVENTS</h5>
        <h1><span>Best Prices</span> This Year</h1>
        <p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do <br> eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
        <button>See Events</button>
    </div>
</section>

<!-- UPCOMING EVENTS -->
<section id="feature">
    <div class="container text-center mt-4 py-2">
        <h3>Events</h3>
        <hr>
        <p>Browse the upcoming and latest events!</p>
    </div>

    <div class="dropdown text-center container py-3">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Categories
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" href="#">Jazz</a>
            <a class="dropdown-item" href="#">Pop</a>
            <a class="dropdown-item" href="#">Rock</a>
            <a class="dropdown-item" href="#">RnB</a>
            <a class="dropdown-item" href="#">Country</a>
            <a class="dropdown-item" href="#">HipHop</a>
            <a class="dropdown-item" href="#">Others</a>
        </div>
    </div>

    <div class="row mx-auto container-fluid">
        {% for i in range(12) %}
        <div class="col-lg-3 col-md-3 col-6 mb-4">
            <div class="card h-100" style="padding: 20px">
                <img class="card-img-top" src="static/Images/albumcover{{ i+1 }}.jpg" alt="Album Cover">
                <div class="card-body text-center">
                    <h5 class="card-title p-date">April 10th 2026: Status : ACTIVE</h5>
                    <h3 class="card-title p-name">Artist Name</h3>
                    <h4 class="card-text p-price">$200.00</h4>
                    <a href="{{ url_for('event.list_events') }}" class="btn btn-primary" 
                    style="background-color: #1d1d1d; font-size: 0.8rem; border: none; font-weight: 700; 
                    color: aliceblue; padding: 13px 30px; cursor: pointer; text-transform: 
                    uppercase;">
                        Buy Ticket
                    </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</section>

{% endblock %}

RhythmRally/templates/loginform.html
<!doctype html>
<html lang="en">
  <head background-color = "grey">
    
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" href="static/style/style.css">

    <title>Rhythm Rally Home</title>
  </head>

  <body>
    
<!-- NAVIGATION BAR -->
<nav class="navbar navbar-expand-lg navbar-light bg-light py-3 fixed-top">
  <a class="navbar-brand" href="#">Rhythm Rally</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">

      <li class="nav-item">
        <a class="nav-link" href="{{url_for('main.home')}}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('main.event_details')}}">Events</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('main.book_event')}}">Create Events</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('main.booking_history')}}">Booking History</a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="{{url_for('main.login_form')}}">Login or Signup</a>
        </li>
     
  </div>
</nav>

<section>
    <div class="container mt-5 pt-5">
        <div class="row">
            <div class="col-12 col-sm-8 col-md-6 m-auto">
                <div class="card border-0 shadow">
                    <div class="card-body">
                        <div class="text-center"><svg class="mx-auto" xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-person-circle" viewBox="0 0 16 16">
                            <path d="M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0"/>
                            <path fill-rule="evenodd" d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1"/>
                          </svg>
                        </div>
                        <form action="">
                            <input type="text" name="" id="" class="form-control my-4 py-2" placeholder="Username">
                            <input type="text" name="" id="" class="form-control my-4 py-2" placeholder="Password">
                            <div class="text-center mt-3">
                                <button class="btn btn-primary">Login</button>
                                <a href="register.html" class="nav-link">Dont have an acccout?</a>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


<!-- FOOTER -->
<footer class="mt-5 py=5">
    <div class="row container mx-auto pt-5">
      <div class="footer-one col-lg-3 col-md-6 col-12">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
      </div>
      <div class="footer-one col-lg-3 col-md-6 col-12">
        <h5 class="pb-2">Categories</h5>
        <ul class="text-uppercase list-unstyled">
          <li><a href="#">Rock</a></li>
          <li><a href="#">Pop</a></li>
          <li><a href="#">Country</a></li>
          <li><a href="#">RnB</a></li>
          <li><a href="#">HipHop</a></li>
        </ul>
      </div>
      <div class="footer-one col-lg-3 col-md-6 col-12">
        <h5 class="pb-2">Contact Us</h5>
        <div>
          <h6 class="text-uppercase">Address</h6>
          <p>123 STREET NAME, CITY, AUSTRALIA</p>
        </div>
        <div>
          <h6 class="text-uppercase">Phone</h6>
          <p>(64+) 0412345678</p>
        </div>
        <div>
          <h6 class="text-uppercase">Email</h6>
          <p>emailaddress@example.com</p>
        </div>
      </div>
      <div class="footer-one col-lg-3 col-md-6 col-12">
        <h5 class="pb-2">Socials</h5>
        <div class="row">
          <img class="img-fluid w-25 h-100 m-2" src="static/Images/instagram.jpg" alt="">
          <img class="img-fluid w-25 h-100 m-2" src="static/Images/twitter.jpg" alt="">
          <img class="img-fluid w-25 h-100 m-2" src="static/Images/youtube.jpg" alt="">
        </div>
        
      </div>
    </div>
  </footer>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

RhythmRally/templates/user.html
{% extends "base.html" %}

{% set body_class = "body" %}

{% from 'bootstrap5/form.html' import render_form %}

{% block content %}


<div class="container mt-5">
    <div class="row justify-content-center align-items-center form-container">
        <div class="col-md-6 mb-5">
            <h4 class="text-center">{{ heading }}</h4>
            <form action="{{ url_for('auth.login') if heading == 'Login' else url_for('auth.register') }}" method="POST">
                {{ render_form(form) }}
                <button type="submit" class="btn btn-primary w-100 mt-3">
                    {{ 'Login' if heading == 'Login' else 'Register' }}
                </button>
            </form>
        </div>

        {% if heading|lower == 'login' %}
        <div class="col-md-4 mb-5">
            <p>New User? <a href="{{ url_for('auth.register') }}">Register here</a>.</p>
        </div>
        {% endif %}
    </div>
</div>

{% endblock %}